import * as React from 'react';

interface AuditReportEmailProps {
  email: string;
  totalSavings: number;
  annualSavings: number;
  shareUrl: string;
  recommendationsCount: number;
}

export const AuditReportEmail: React.FC<AuditReportEmailProps> = ({
  email,
  totalSavings,
  annualSavings,
  shareUrl,
  recommendationsCount,
}) => (
  <div style={{
    fontFamily: 'Arial, sans-serif',
    maxWidth: '600px',
    margin: '0 auto',
    padding: '20px',
  }}>
    <div style={{
      backgroundColor: '#1e3a8a', // StackAudit Trust Blue
      padding: '30px',
      textAlign: 'center',
      borderRadius: '12px 12px 0 0',
    }}>
      <h1 style={{ color: 'white', margin: 0, fontSize: '22px', letterSpacing: '0.05em', textTransform: 'uppercase' }}>StackAudit Intelligence Report</h1>
    </div>
    
    <div style={{
      backgroundColor: 'white',
      padding: '30px',
      borderRadius: '0 0 12px 12px',
      boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
      border: '1px solid #e5e7eb',
      borderTop: 'none',
    }}>
      {totalSavings > 0 ? (
        <>
          <div style={{ textAlign: 'center', marginBottom: '30px' }}>
            <div style={{ fontSize: '48px', marginBottom: '10px' }}>💰</div>
            <h2 style={{ color: '#059669', fontSize: '36px', margin: '0' }}>
              Save ${totalSavings}/month
            </h2>
            <p style={{ color: '#6b7280', fontSize: '18px' }}>
              ${annualSavings}/year
            </p>
          </div>
          
          <p style={{ fontSize: '16px', lineHeight: '1.5', marginBottom: '20px' }}>
            Great news! We identified <strong>{recommendationsCount} optimization {recommendationsCount === 1 ? 'opportunity' : 'opportunities'}</strong> 
            within your AI infrastructure.
          </p>
          
          <div style={{
            backgroundColor: '#f0fdf4',
            borderLeft: '4px solid #059669',
            padding: '15px',
            marginBottom: '25px',
          }}>
            <p style={{ margin: 0, fontSize: '14px', color: '#166534' }}>
              <strong>Next Steps:</strong>
            </p>
            <p style={{ margin: '10px 0 0 0', fontSize: '14px', color: '#166534' }}>
              1. Review your full audit report<br />
              2. Implement the recommended changes<br />
              3. Start saving on your AI tools
            </p>
          </div>
        </>
      ) : (
        <>
          <div style={{ textAlign: 'center', marginBottom: '30px' }}>
            <div style={{ fontSize: '48px', marginBottom: '10px' }}>✅</div>
            <h2 style={{ color: '#1e3a8a', fontSize: '28px', margin: 0 }}>
              Infrastructure Optimized
            </h2>
          </div>
          
          <p style={{ fontSize: '16px', lineHeight: '1.5', marginBottom: '20px' }}>
            Your AI infrastructure demonstrates peak financial efficiency. No immediate redundancies detected.
          </p>
        </>
      )}
      
      <a
        href={shareUrl}
        style={{
          display: 'block',
          backgroundColor: '#1e3a8a',
          color: 'white',
          textAlign: 'center',
          padding: '14px',
          borderRadius: '8px',
          textDecoration: 'none',
          fontWeight: 'bold',
          marginTop: '25px',
        }}
      >
        View Certified Audit Report →
      </a>
      
      <hr style={{ margin: '30px 0 20px', border: 'none', borderTop: '1px solid #e5e7eb' }} />
      
      <p style={{ fontSize: '12px', color: '#9ca3af', textAlign: 'center', margin: 0 }}>
        This report was generated by StackAudit for {email}.
        Unsubscribe by replying &ldquo;stop&rdquo;.
      </p>
    </div>
  </div>
);